"""Migração Inicial

Revision ID: 6e126e222957
Revises: 
Create Date: 2024-01-20 18:57:50.796794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e126e222957'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Perfis',
    sa.Column('CodPerfil', sa.Integer(), nullable=False),
    sa.Column('DescPerfil', sa.String(length=50), nullable=True),
    sa.Column('PerfilAdministrador', sa.CHAR(length=1), nullable=True),
    sa.Column('DataAtualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('CodPerfil')
    )
    op.create_index(op.f('ix_Perfis_CodPerfil'), 'Perfis', ['CodPerfil'], unique=False)
    op.create_table('Transacoes',
    sa.Column('CodTransacao', sa.Integer(), nullable=False),
    sa.Column('DescTransacao', sa.String(length=100), nullable=True),
    sa.Column('TipoTransacao', sa.String(length=25), nullable=True),
    sa.Column('DataAtualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('CodTransacao')
    )
    op.create_index(op.f('ix_Transacoes_CodTransacao'), 'Transacoes', ['CodTransacao'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_descr'), 'permissions', ['descr'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('Acessos',
    sa.Column('CodPerfil', sa.Integer(), nullable=False),
    sa.Column('CodTransacao', sa.Integer(), nullable=False),
    sa.Column('Inclui', sa.CHAR(length=1), nullable=True),
    sa.Column('Altera', sa.CHAR(length=1), nullable=True),
    sa.Column('Exclui', sa.CHAR(length=1), nullable=True),
    sa.Column('Executa', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['CodPerfil'], ['Perfis.CodPerfil'], ),
    sa.ForeignKeyConstraint(['CodTransacao'], ['Transacoes.CodTransacao'], ),
    sa.PrimaryKeyConstraint('CodPerfil', 'CodTransacao')
    )
    op.create_table('Usuarios',
    sa.Column('Numero', sa.Integer(), nullable=False),
    sa.Column('Iniciais', sa.String(length=10), nullable=True),
    sa.Column('CodPerfil', sa.Integer(), nullable=True),
    sa.Column('Nome', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.CHAR(length=1), nullable=True),
    sa.Column('Senha', sa.String(length=200), nullable=True),
    sa.Column('IdRecuperaSenha', sa.String(length=20), nullable=True),
    sa.Column('ResetouSenha', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['CodPerfil'], ['Perfis.CodPerfil'], ),
    sa.PrimaryKeyConstraint('Numero')
    )
    op.create_index(op.f('ix_Usuarios_Iniciais'), 'Usuarios', ['Iniciais'], unique=False)
    op.create_index(op.f('ix_Usuarios_Numero'), 'Usuarios', ['Numero'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_fullname'), 'users', ['fullname'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_fullname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_Usuarios_Numero'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_Iniciais'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_table('Acessos')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_descr'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_Transacoes_CodTransacao'), table_name='Transacoes')
    op.drop_table('Transacoes')
    op.drop_index(op.f('ix_Perfis_CodPerfil'), table_name='Perfis')
    op.drop_table('Perfis')
    # ### end Alembic commands ###
